{{- if and .Values.valkey.enabled .Values.valkey.auth.enabled .Values.valkey.auth.password (not .Values.valkey.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "colanode.fullname" . }}-valkey
  labels:
    {{- include "colanode.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
type: Opaque
data:
  {{ .Values.valkey.auth.passwordKey }}: {{ .Values.valkey.auth.password | b64enc | quote }}
{{- end }} 