apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twentycrm-worker
  name: twentycrm-worker
  namespace: twentycrm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: twentycrm-worker
  template:
    metadata:
      labels:
        app: twentycrm-worker
    spec:
      containers:
        - name: twentycrm
          image: twentycrm/twenty:latest
          imagePullPolicy: Always
          env:
            - name: SERVER_URL
              value: "https://crm.example.com:443"
            - name: PG_DATABASE_URL
              value: {{ if .Values.database.external.enabled }}{{ if .Values.database.external.url }}"{{ .Values.database.external.url }}"{{ else }}"postgres://{{ .Values.database.external.username }}:{{ .Values.database.external.password }}@{{ .Values.database.external.host }}:{{ .Values.database.external.port }}/{{ .Values.database.external.database }}"{{ end }}{{ else }}"postgres://postgres:postgres@twentycrm-db.twentycrm.svc.cluster.local/default"{{ end }}
            - name: DISABLE_DB_MIGRATIONS
              value: "true"
            - name: STORAGE_TYPE
              value: "local"
            - name: "REDIS_URL"
              value: {{ if .Values.redis.external.enabled }}{{ if .Values.redis.external.url }}"{{ .Values.redis.external.url }}"{{ else }}"redis://{{ if .Values.redis.external.password }}:{{ .Values.redis.external.password }}@{{ end }}{{ .Values.redis.external.host }}:{{ .Values.redis.external.port }}"{{ end }}{{ else }}"redis://twentycrm-redis.twentycrm.svc.cluster.local:6379"{{ end }}
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: tokens
                  key: accessToken
          command:
            - yarn
            - worker:prod
          resources:
            requests:
              memory: "1024Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          stdin: true
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
