{{- if .Values.server.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "colanode.fullname" . }}-server
  labels:
    {{- include "colanode.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "colanode.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
{{- end }}