apiVersion: v2
appVersion: 1.115.1
dependencies:
- condition: valkey.enabled
  name: valkey
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.4.7
description: Helm Chart for deploying n8n on Kubernetes, based on 8gears n8n chart
home: https://github.com/victorlane/Helm-Charts
icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
keywords:
- Workflow Automation
- Workflow
- iPaaS
- integration-framework
- low-code-plattform
- low-code
maintainers:
- name: Victor Brinkhorst
  email: victor@bmlabs.eu
  url: https://github.com/victorlane
name: n8n
sources:
- https://github.com/8gears/n8n-helm-chart
- https://github.com/n8n-io/n8n
- https://n8n.io/
type: application
version: 1.0.18
