apiVersion: v2
name: colanode
description: A Helm chart for Colanode
type: application
version: 0.3.0
appVersion: '1.0.0'

home: https://github.com/victorlane/Helm-Charts
sources:
- https://github.com/colanode/colanode/tree/main/hosting/kubernetes

keywords:
- productivity
- collaboration
