apiVersion: v2
name: colanode
description: A Helm chart for Colanode
type: application
version: 0.2.6
appVersion: '1.0.0'

home: https://github.com/victorlane/Helm-Charts
sources:
- https://github.com/colanode/colanode/tree/main/hosting/kubernetes

keywords:
- productivity
- collaboration

dependencies:
- name: postgresql
  version: '16.7.4'
  repository: 'https://charts.bitnami.com/bitnami'
  condition: postgresql.enabled
- name: minio
  version: '16.0.10'
  repository: 'https://charts.bitnami.com/bitnami'
  condition: minio.enabled
